#!/usr/bin/env bash

# one-time setup script

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"
BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.config/nas-bot"
COMMAND_DIR="$REPO_DIR/daemon/command"
PYTHON_BIN="$REPO_DIR/venv/bin/python3"

# Helper: check if a path is tracked in git (not ignored/untracked)
is_tracked_in_git() {
  local path="$1"
  # Returns 0 if tracked, non-zero if ignored/untracked
  git -C "$REPO_DIR" ls-files --error-unmatch "$path" &>/dev/null
}

if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "Error: venv not found at $REPO_DIR/venv — run 'python3 -m venv venv && venv/bin/pip install requests python-dotenv' first." >&2
  exit 1
fi

echo "Installing nas-bot from: $REPO_DIR"

mkdir -p "$SYSTEMD_USER_DIR" "$BIN_DIR" "$CONFIG_DIR"

# ── Bot-level secrets (BOT_TOKEN, CHAT_ID, ALLOWED_USER_IDS) ────────────
if [[ ! -f "$CONFIG_DIR/secrets" ]]; then
  cp "$REPO_DIR/secrets.example" "$CONFIG_DIR/secrets"
  chmod 600 "$CONFIG_DIR/secrets"
  echo ">>> Created $CONFIG_DIR/secrets from template — edit it with your real BOT_TOKEN and CHAT_ID before starting anything."
else
  echo "Secrets file already exists at $CONFIG_DIR/secrets — leaving it alone."
fi

# ── Per-command config (.env per command folder) ───────────────────────
if [[ -d "$COMMAND_DIR" ]]; then
  for cmd_dir in "$COMMAND_DIR"/*/; do
    [[ -f "$cmd_dir/.env.example" ]] || continue
    cmd_name=$(basename "$cmd_dir")
    
    # Skip gitignored/untracked commands
    if ! is_tracked_in_git "daemon/command/$cmd_name/.env.example"; then
      echo "Skipping untracked command: $cmd_name (gitignored or not committed)"
      continue
    fi
    
    if [[ ! -f "$cmd_dir/.env" ]]; then
      cp "$cmd_dir/.env.example" "$cmd_dir/.env"
      echo ">>> Created $cmd_dir.env from template — edit it for your system before this command will work (see $cmd_dir/README.md)."
    else
      echo "Config already exists at $cmd_dir.env — leaving it alone."
    fi
    chmod +x "$cmd_dir"/*.py 2>/dev/null || true
  done
fi

chmod +x "$REPO_DIR/daemon/nasbot.py"

# ── Symlink daemon for manual CLI use (optional convenience) ──────────
ln -sf "$REPO_DIR/daemon/nasbot.py" "$BIN_DIR/nasbot"

# ── Generate systemd --user units ──────────────────────────────────────
# Each command directory's .env declares its own schedule(s). Adding a new
# scheduled command requires no edit to this script — only a .env with
# TIMER_INTERVAL / TIMER_CALENDAR (and optionally the _SECONDARY pair).
# See daemon/command/diskcheck/.env.example for the key reference.

# emit_pair <cmd_name> <cmd_dir> <unit_suffix> <run_mode> <interval> <calendar> <persistent> <on_boot> <entry_script>
emit_pair() {
  local cmd_name="$1" cmd_dir="$2" unit_suffix="$3" run_mode="$4"
  local interval="$5" calendar="$6" persistent="$7" on_boot="$8" entry_script="$9"

  # Nothing declared for this pair — nothing to generate.
  if [[ -z "$interval" && -z "$calendar" ]]; then
    return 0
  fi

  if [[ -n "$interval" && -n "$calendar" ]]; then
    echo "Error: '$cmd_name' sets both an interval and a calendar schedule" \
         "for the same pair (suffix: '${unit_suffix:-primary}')." >&2
    echo "       Each schedule pair must use exactly one of TIMER_INTERVAL" \
         "or TIMER_CALENDAR (and their _SECONDARY equivalents), not both." >&2
    exit 1
  fi

  local unit_stem="${cmd_name}${unit_suffix}"
  local service_file="$SYSTEMD_USER_DIR/${unit_stem}.service"
  local timer_file="$SYSTEMD_USER_DIR/${unit_stem}.timer"

  cat > "$service_file" <<EOF
# Generated by install.sh from $cmd_dir/.env — do not edit by hand.
[Unit]
Description=nas-bot $cmd_name ($run_mode)
After=default.target

[Service]
Type=oneshot
ExecStart=$PYTHON_BIN $cmd_dir/$entry_script $run_mode
EOF

  {
    echo "# Generated by install.sh from $cmd_dir/.env — do not edit by hand."
    echo "[Unit]"
    echo "Description=nas-bot $cmd_name timer"
    echo ""
    echo "[Timer]"
    if [[ -n "$on_boot" ]]; then
      echo "OnBootSec=$on_boot"
    fi
    if [[ -n "$interval" ]]; then
      echo "OnUnitActiveSec=$interval"
    else
      echo "OnCalendar=$calendar"
    fi
    echo "Persistent=${persistent:-true}"
    echo ""
    echo "[Install]"
    echo "WantedBy=timers.target"
  } > "$timer_file"

  echo "  generated: ${unit_stem}.service, ${unit_stem}.timer"
}

echo ""
echo "Generating scheduled units from per-command .env files..."

# Clean up legacy units from command renames (e.g., disk-check → diskcheck)
# This prevents duplicate schedules when a command is renamed but old units remain enabled
LEGACY_UNITS=(
  "disk-check.service"
  "disk-check.timer"
  "disk-check-secondary.service"
  "disk-check-secondary.timer"
)

for unit in "${LEGACY_UNITS[@]}"; do
  if systemctl --user list-unit-files "$unit" 2>/dev/null | grep -q "$unit"; then
    echo "Removing legacy unit: $unit"
    systemctl --user stop "$unit" 2>/dev/null || true
    systemctl --user disable "$unit" 2>/dev/null || true
    rm -f "$SYSTEMD_USER_DIR/$unit"
  fi
done

if [[ -d "$COMMAND_DIR" ]]; then
  for cmd_dir in "$COMMAND_DIR"/*/; do
    cmd_dir="${cmd_dir%/}"
    cmd_name=$(basename "$cmd_dir")
    [[ -f "$cmd_dir/.env" ]] || continue

    # Skip gitignored/untracked commands — only install what's committed
    if ! is_tracked_in_git "daemon/command/$cmd_name/.env.example"; then
      echo "Skipping timer generation for untracked command: $cmd_name"
      continue
    fi

    # Filter to only process git-tracked directories
    if ! is_tracked_in_git "$cmd_dir"; then
      continue
    fi

    (
      set -a
      # shellcheck disable=SC1090
      source "$cmd_dir/.env"
      set +a

      entry_script="${ENTRY_SCRIPT:-$cmd_name.py}"

      emit_pair "$cmd_name" "$cmd_dir" "" \
        "${RUN_MODE:---send}" \
        "${TIMER_INTERVAL:-}" "${TIMER_CALENDAR:-}" \
        "${TIMER_PERSISTENT:-true}" "${TIMER_ON_BOOT:-}" \
        "$entry_script"

      if [[ -n "${TIMER_INTERVAL_SECONDARY:-}${TIMER_CALENDAR_SECONDARY:-}" ]]; then
        emit_pair "$cmd_name" "$cmd_dir" "-secondary" \
          "${RUN_MODE_SECONDARY:---send}" \
          "${TIMER_INTERVAL_SECONDARY:-}" "${TIMER_CALENDAR_SECONDARY:-}" \
          "${TIMER_PERSISTENT_SECONDARY:-true}" "${TIMER_ON_BOOT_SECONDARY:-}" \
          "$entry_script"
      fi
    )
  done
fi

# nasbot daemon (long-running, listens for Telegram commands) — static.
cat > "$SYSTEMD_USER_DIR/nasbot.service" <<EOF
[Unit]
Description=nas-bot Telegram command listener
After=network.target

[Service]
ExecStart=$PYTHON_BIN $REPO_DIR/daemon/nasbot.py
WorkingDirectory=$REPO_DIR/daemon
Environment=PYTHONUNBUFFERED=1
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF

if ! systemctl --user daemon-reload; then
  echo "Error: 'systemctl --user daemon-reload' failed." >&2
  echo "       Check the generated unit files under $SYSTEMD_USER_DIR for" \
       "syntax errors (e.g. a malformed OnCalendar expression)." >&2
  exit 1
fi

echo ""
echo "Install complete. Next steps:"
echo "  1. Edit bot secrets:   \$EDITOR $CONFIG_DIR/secrets"
echo "  2. Edit each command's config (created from .env.example wherever missing — see messages above)"
echo "  3. Enable lingering:   sudo loginctl enable-linger \$USER   (one-time, as root)"
echo "  4. Enable and start units, e.g.:"
systemctl --user list-unit-files 2>/dev/null \
  | awk '/\.timer$/ {print "       systemctl --user enable --now " $1}' \
  || true
echo "       systemctl --user enable --now nasbot.service"
echo ""
echo "  Tip: run 'systemctl --user list-timers' any time to see everything"
echo "       currently scheduled, including anything left over from a"
echo "       command you've since removed or reconfigured."
